Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace GameVault.Models
{
    public class AppUser : IdentityUser
    {
        public virtual ICollection<Jogo> Jogos { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

Models/Enums/Genero.cs
namespace GameVault.Models.Enums
{
    public enum Genero
    {
        ACAO,
        AVENTURA,
        RPG,
        ESTRATEGIA,
        SIMULACAO,
        ESPORTES,
        CORRIDA,
        LUTA,
        PLATAFORMA,
        PUZZLE,
        SURVIVAL_HORROR,
        SANDBOX,
        MMO,
        MOBA,
        ROGUELIKE,
        STEALTH,
        BATTLE_ROYALE,
        TOWER_DEFENSE,
        VISUAL_NOVEL,
        RITMO
    }
}

Models/Enums/Plataforma.cs
namespace GameVault.Models.Enums
{
    public enum Plataforma
    {
        PC,
        XBOX,
        PLAYSTATION,
        NINTENDO,
        MOBILE
    }
}

Models/ErrorViewModel.cs
namespace GameVault.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Jogo.cs
using GameVault.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace GameVault.Models
{
    public class Jogo
    {
        [Key]
        public int JogoId { get; set; }

        [Required(ErrorMessage = "O nome do jogo deve ser informado")]
        [Display(Name = "Nome do Jogo")]
        [StringLength(80, MinimumLength = 4, ErrorMessage = "O {0} deve ter no mínimo {2} e no máximo {1} caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "A descrição do jogo deve ser informada")]
        [Display(Name = "Descrição do Jogo")]
        [MinLength(20, ErrorMessage = "Descrição deve ter no mínimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrição pode exceder {1} caracteres")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "A plataforma do jogo deve ser informada")]
        [Display(Name = "Plataforma do Jogo")]
        [StringLength(80, MinimumLength = 1, ErrorMessage = "A {0} deve ter no mínimo {2} e no máximo {1} caracteres")]
        public string Plataforma { get; set; }

        [Required(ErrorMessage = "Os gêneros do jogo devem ser informados")]
        [Display(Name = "Gêneros do Jogo")]
        [StringLength(200, MinimumLength = 1, ErrorMessage = "O {0} deve ter no mínimo {2} e no máximo {1} caracteres")]
        public string Generos { get; set; }
        public int ReviewId { get; set; }
        public Review Review { get; set; }
        public string AppUserId { get; set; }
        public AppUser AppUser { get; set; }
    }
}

Models/Review.cs
using System.ComponentModel.DataAnnotations;

namespace GameVault.Models
{
    public class Review
    {
        [Key]
        public int ReviewId { get; set; }

        [Required(ErrorMessage = "O comentário da review deve ser informado")]
        [Display(Name = "Comentário da Review")]
        [MinLength(4, ErrorMessage = "O comentário deve ter no mínimo 4 caracteres")]
        [MaxLength(200, ErrorMessage = "O comentário não pode exceder 200 caracteres")]
        public string Comentario { get; set; }

        [Required(ErrorMessage = "Informe a nota da review")]
        [Display(Name = "Nota")]
        [Range(1, 10, ErrorMessage = "A nota deve estar entre 1 e 10")]
        public int Nota { get; set; }

        [Display(Name = "Data da Review")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy hh:mm}", ApplyFormatInEditMode = true)]
        public DateTime DataAvaliacao { get; set; }

        [Required(ErrorMessage = "Informe o tempo de jogo")]
        [Display(Name = "Tempo de Preparo")]
        [DisplayFormat(DataFormatString = @"{0:hh\:mm}", ApplyFormatInEditMode = true)]
        public int HorasDeJogo { get; set; }
        public int JogoId { get; set; }
        public Jogo Jogo { get; set; }
        public string AppUserId { get; set; }
        public AppUser AppUser { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using GameVault.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameVault.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JogoController.cs
using GameVault.Models;
using GameVault.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Security.Claims;

namespace GameVault.Controllers
{
    public class JogoController : Controller
    {
        private readonly IJogoRepository _jogoRepository;
        public JogoController(IJogoRepository jogoRepository)
        {
            _jogoRepository = jogoRepository;
        }

        public IActionResult List()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var jogos = _jogoRepository.GetAllJogosPerUser(userId).ToList();
            return View(jogos);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Jogo jogo)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                jogo.AppUserId = userId;

                _jogoRepository.AddJogo(jogo);
                return RedirectToAction("List");
            }
            return View(jogo);
        }

        public IActionResult Delete(int jogoId)
        {
            _jogoRepository.DeleteJogo(jogoId);
            return RedirectToAction("List");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Jogo/Add.cshtml
@model Jogo
<div class="mb-4">


	<form asp-action="Add" method="post">
		<div class="row">
			<div class="col-4">
				<label asp-for="Nome">Nome</label>
				<input asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>
			<div class="col-8">
				<label asp-for="Descricao">Descrição</label>
				<input asp-for="Descricao" class="form-control" />
				<span asp-validation-for="Descricao" class="text-danger"></span>
			</div>
		</div>
		<div class="row">
			<div class="col-6">
				<label asp-for="Generos">Gêneros</label>
				<input asp-for="Generos" class="form-control" />
				<span asp-validation-for="Generos" class="text-danger"></span>
			</div>
			<div class="col-6">
				<label asp-for="Plataforma">Plataforma</label>
				<input asp-for="Plataforma" class="form-control" />
				<span asp-validation-for="Plataforma" class="text-danger"></span>
			</div>
		</div>

		<div class="form-group" style="margin-top:10px">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</form>
</div>

Views/Jogo/List.cshtml
@model IEnumerable<GameVault.Models.Jogo>

@{
	ViewData["Title"] = "List";
}
<div class="container">
	<h1>Meus Jogos</h1>

	<p>
		<a asp-action="Add">
			<button type="button" class="btn btn-outline-primary">Adicionar Jogo</button>
		</a>
	</p>
	<div class="row">
		@foreach (var item in Model)
		{
			<div class="col-md-3 mb-3">
				<partial name="_JogoPartial" for="@item" />
			</div>
		}
	</div>
</div>

Views/Shared/_JogoPartial.cshtml
@model Jogo

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Nome</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">@Model.Generos</h6>
        <h6 class="card-subtitle mb-2 text-body-secondary">@Model.Plataforma</h6>
        <p class="card-text">@Model.Descricao</p>
        @if (Model.ReviewId > 0){
            <a href="#" class="card-link">Ver a analise</a>
        }else{
            <a href="#" class="card-link">Avaliar</a>
        }
        <a asp-controller="Jogo" asp-action="Delete" asp-route-jogoId="@Model.JogoId" class="card-link text-danger">Excluir</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameVault</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameVault.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameVault</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jogo" asp-action="List">Meus Jogos</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GameVault - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>